### ISSUE TITLE
bug: able to edit column value to empty string

### ISSUE THREAD

**Issue by Oiko78** [CharlesKristov/DB-WebApp#2]
Insert empty string bener gabisa tapi kalo edit jadi empty string bisa

### Before edit:
![image](https://user-images.githubusercontent.com/70620781/147810056-90e0d737-93c8-4cac-802f-43dcd5b2ff6f.png)

### After edit:
![image](https://user-images.githubusercontent.com/70620781/147810122-a0dd9c04-9972-4e55-9d31-9e0496ea75bf.png)

Di database keitungnya jadi empty string `''` padahal di databasenya udah `not null`

**Comment by agusthas** [comment]
@Oiko78 Gimana kalo kita ubah untuk `input` yang type nya `text` itu jadi required?

`<input type="text" class="form-control" name=<?= $column['name'] ?> value=<?= $column['value'] ?> required>`

Jadi nanti kalo saat edit tapi itu empty string, nanti gabisa ke edit.

**Comment by CharlesKristov** [comment]
wah cerdas made bole juga
